on:
  schedule:
    - cron: '*/30 * * * *'

name: Check AEGIS API Status

jobs:
  check_api_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Status
        id: api_status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://httpstat.us/400)
          echo "::set-env name=GITHUB_STATE::${response}"

      - name: Use API Status
        run: |
          if [ "${{ env.GITHUB_STATE }}" = "200" ]; then
            echo "API endpoint is up and running"
          else
            echo "API endpoint is not accessible"

            - name: Notify if API endpoint is not accessible
              uses: cinotify/github-action@v1.6.0
              env:
                GITHUB_OUTPUT: |
                  to=conales.jt@pg.com
                  subject=AEGIS API Endpoint Status
                  body=The AEGIS API endpoint is not accessible. The API status is ${{ env.GITHUB_STATE }}. Please investigate.
              run: echo "$GITHUB_OUTPUT" > $GITHUB_ENV
          fi
