on:
  schedule:
    # Run every hour, on the hour. This can be customized to checking as frequently as every 5 minutes.
    - cron: '*/5 * * * *'

name: Check for API Status

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data
        run: curl "http://gadc-automat01.na.pg.com:8330/isAlive" -o data.json

      - name: Parse data
        id: parse_data
        run: echo '::set-output name=someField::'$(jq -r '.someField' data.json)

      - name: Compare Variables
        run: |
          if [ "${{ env.someField }}" = "Hi, I am alive." ]; then
            echo "API Status:" - ${{ env.someField }}
          else
            echo "API endpoint cannot be accessed"
            # If the response is different, notify me via email
            - name: Notify if data has changed
              uses: cinotify/github-action@v1.6.0
              with:
                # Recipient email address
                to: conales.jt@pg.com
                # Email subject
                subject: Aegis API Status
                # Email body
                body: API endpoint cannot be accessed. Status - ${{ env.someField }}
          fi 
    
  


      
