name: Debug API Access

on: 
  workflow_dispatch:

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check connectivity
      run: |
        echo "Checking connectivity to API endpoint"
        ping -c 4 azw-dxcapautd02.int.pg.com

    - name: Test API access
      run: |
        echo "Testing API access"
        curl -v http://azw-dxcapautd02.int.pg.com:5101/isAlive
