name: Debug API Access

on:
  workflow_dispatch:

jobs:
  check_api_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check API Status
        id: aegis_api_status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 http://azw-dxcapautp02.int.pg.com:5101/isAlive)
          body=$(curl -s http://azw-dxcapautp02.int.pg.com:5101/isAlive)
          echo "API status: ${response}"
          echo "API response body: ${body}"
          echo "API_STATUS=${response}" >> $GITHUB_ENV
          echo "API_BODY=${body}" >> $GITHUB_ENV

      - name: Print All API Statuses and Bodies
        run: |
          echo "API status: ${{ env.API_STATUS }}"
          echo "API response body: ${{ env.API_BODY }}"
