name: Check API Status V3

on:
 workflow_dispatch:
 
jobs:
  check_api_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Status
        id: api_status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://httpstat.us/404)
          echo "STATE=${response}" >> $GITHUB_ENV

      - name: Use API Status
        id: api_status_check
        run: |
          if [ "${{ env.STATE }}" = "200" ]; then
            echo "API endpoint is up and running"
            echo "send_email=false" >> $GITHUB_ENV
          else
            echo "API endpoint is not accessible"
            echo "send_email=true" >> $GITHUB_ENV
          fi

      - name: Send Email
        if: env.send_email == 'true'
        uses: cinotify/github-action@v1.6.0
        with:
          to: "conales.jt@pg.com, "
          subject: "API Endpoint Status"
          body: "The API endpoint is not accessible. The API status is ${{ env.STATE }}. Please investigate."
          type: "text/html"
