name: Insert Data into MongoDB

on: 
  workflow_dispatch:

jobs:
  insert-mongo-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo

    - name: Insert data into MongoDB
      env:
        MONGODB_URI: ${{ secrets.MONGODB_CONNECTION_STRING }}
        DATABASE_NAME: FTATLogs
        COLLECTION_NAME: FTAT Logs
        NAME: "Aegis"
        STATUS: "active"
        DATETIME: "2024-08-14 19:15:00"
        
      run: |
        python -c "from pymongo import MongoClient; \
                   from datetime import datetime; \
                   import os; \
                   client = MongoClient(os.environ['MONGODB_URI']); \
                   db = client[os.environ['DATABASE_NAME']]; \
                   collection = db[os.environ['COLLECTION_NAME']]; \
                   document = {'name': os.environ['NAME'], 'status': os.environ['STATUS'], 'date': datetime.strptime(os.environ['DATETIME'], '%Y-%m-%d %H:%M:%S')}; \
                   collection.insert_one(document); \
                   print('Data inserted successfully.')"
